### PR TITLE
Just blew this thing up, 

### PR DESCRIPTION
**Pull request by Seeker1911**
please actually fetch branch and make really sure it works. cleaned up code, comments, docstrings, and removed class references.

### CODE REVIEW

**Comment by benwilburn** [comment]
error on line 56 in main.py

**Comment by benwilburn** [comment]
didn't end parentheses on line 55

**Comment by CoryTohill** [comment]
👍 🔕 🎁

**Comment by pbhowelljr** [comment]
:+1:

**Pull request merged**
